Added tenure rate change feature with cp-invest interaction for function
crednet/invest-sdk pull request #74
Opened 2023-09-12 13:28 UTC by Ishogbon

2023-09-12 13:55 UTC, cheezytony requested changes

2023-09-14 09:33 UTC, cheezytony commented on src/Http/Requests/RateUpdateRequest.php
> +            'percentage' => 'required|numeric|min:0|max:30'
I think it's best to set the max to 100%, to avoid coming back to change it in code

2023-09-14 09:37 UTC, Ishogbon commented on src/Http/Requests/RateUpdateRequest.php
> +            'percentage' => 'required|numeric|min:0|max:30'
Alright boss!

2023-09-14 10:34 UTC, cheezytony approved these changes

2023-09-14 10:34 UTC, merged